version: "3.7"
services: 
  db: 
    image: mongo:3.4
  test:
    ports: 
      - 3000:3000
    build: .
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
    entrypoint: bundle exec rspec

